[build]
    functions = "functions"

[[redirects]]
    to = "/.netlify/functions/api/:splat"
    from = "/*"

[functions]
bd = "bd.js"

[[functions.schedule]]
    path = "/.netlify/functions/bd"
    schedule = "*/10 * * * *"